In [28]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [29]:
path_name = "/Users/garciaj42/code/MLFinance/claude"

In [30]:
import sys
print(sys.path)
sys.path.insert(0, path_name)

['/Users/garciaj42/code/MLFinance/claude', '/Users/garciaj42/code/MLFinance/claude/notebooks', '/opt/homebrew/Cellar/python@3.9/3.9.19_1/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/opt/homebrew/Cellar/python@3.9/3.9.19_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/opt/homebrew/Cellar/python@3.9/3.9.19_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload', '', '/opt/homebrew/lib/python3.9/site-packages', '/opt/homebrew/lib/python3.9/site-packages/IPython/extensions', '/Users/garciaj42/.ipython', '/Users/garciaj42/code/MLFinance', '/Users/garciaj42/code/MLFinance']

In [31]:
lookback_days = 8 * 365

In [32]:
import fredapi
# Initialize FRED
fred_api_key='c44011f35ea9b58dc265ab237efaa525'
fred = fredapi.Fred(api_key=fred_api_key)

from fred_collector import create_fred_collector

fc = create_fred_collector(
    fred_api=fred,
    lookback_days=lookback_days
)

# Collect macro data
fred_data = fc.get_historical_fred_data()

INFO:fred_collector:Requesting historical FRED data from 2016-12-24 16:01:25.195383 to 2024-12-22 16:01:25.195383 2920 D

GDP 2014-10-01    17912.079
2015-01-01    18063.529
2015-04-01    18279.784
2015-07-01    18401.626
2015-10-01    18435.137
2016-01-01    18525.933
2016-04-01    18711.702
2016-07-01    18892.639
2016-10-01    19089.379
2017-01-01    19280.084
2017-04-01    19438.643
2017-07-01    19692.595
2017-10-01    20037.088
2018-01-01    20328.553
2018-04-01    20580.912
2018-07-01    20798.730
2018-10-01    20917.867
2019-01-01    21111.600
2019-04-01    21397.938
2019-07-01    21717.171
2019-10-01    21933.217
2020-01-01    21727.657
2020-04-01    19935.444
2020-07-01    21684.551
2020-10-01    22068.767
2021-01-01    22656.793
2021-04-01    23368.861
2021-07-01    23921.991
2021-10-01    24777.038
2022-01-01    25215.491
2022-04-01    25805.791
2022-07-01    26272.011
2022-10-01    26734.277
2023-01-01    27164.359
2023-04-01    27453.815
2023-07-01    27967.697
2023-10-01    28296.967
2024-01-01    28624.069
2024-04-01    29016.714
2024-07-01    29374.914
dtype: float64
UNRATE 2014-12-01    5.6
2015-01-01    5.7
2015-02-01    5.5
2015-03-01    5.4
2015-04-01    5.4
             ...
2024-07-01    4.3
2024-08-01    4.2
2024-09-01    4.1
2024-10-01    4.1
2024-11-01    4.2
Length: 120, dtype: float64
CPIAUCSL 2014-12-01    236.252
2015-01-01    234.747
2015-02-01    235.342
2015-03-01    235.976
2015-04-01    236.222
               ...
2024-07-01    313.534
2024-08-01    314.121
2024-09-01    314.686
2024-10-01    315.454
2024-11-01    316.441
Length: 120, dtype: float64
FEDFUNDS 2014-12-01    0.12
2015-01-01    0.11
2015-02-01    0.11
2015-03-01    0.11
2015-04-01    0.12
              ...
2024-07-01    5.33
2024-08-01    5.33
2024-09-01    5.13
2024-10-01    4.83
2024-11-01    4.64
Length: 120, dtype: float64
T10Y2Y 2014-12-25     NaN
2014-12-26    1.52
2014-12-29    1.50
2014-12-30    1.51
2014-12-31    1.50
              ...
2024-12-16    0.14
2024-12-17    0.15
2024-12-18    0.15
2024-12-19    0.25
2024-12-20    0.22
Length: 2607, dtype: float64
BAMLH0A0HYM2 2014-12-25     NaN
2014-12-26    4.93
2014-12-29    4.96
2014-12-30    4.98
2014-12-31    5.04
              ...
2024-12-13    2.68
2024-12-16    2.69
2024-12-17    2.75
2024-12-18    2.73
2024-12-19    2.91
Length: 2641, dtype: float64
WM2NS 2014-12-29    11799.9
2015-01-05    11830.1
2015-01-12    11807.0
2015-01-19    11762.9
2015-01-26    11687.2
               ...
2024-10-07    21251.3
2024-10-14    21228.1
2024-10-21    21229.8
2024-10-28    21203.1
2024-11-04    21391.7
Length: 515, dtype: float64
INDPRO 2014-12-01    103.6151
2015-01-01    102.7923
2015-02-01    102.1366
2015-03-01    101.7869
2015-04-01    101.2255
                ...
2024-07-01    102.5340
2024-08-01    103.0831
2024-09-01    102.5283
2024-10-01    102.1123
2024-11-01    101.9621
Length: 120, dtype: float64
HOUST 2014-12-01    1073.0
2015-01-01    1085.0
2015-02-01     886.0
2015-03-01     960.0
2015-04-01    1190.0
               ...
2024-07-01    1262.0
2024-08-01    1379.0
2024-09-01    1355.0
2024-10-01    1312.0
2024-11-01    1289.0
Length: 120, dtype: float64
RSAFS 2014-12-01    438509.0
2015-01-01    436125.0
2015-02-01    435450.0
2015-03-01    441895.0
2015-04-01    442967.0
                ...
2024-07-01    710851.0
2024-08-01    710038.0
2024-09-01    716388.0
2024-10-01    719676.0
2024-11-01    724609.0
Length: 120, dtype: float64

/Users/garciaj42/code/MLFinance/claude/fred_collector.py:149: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  features = features.fillna(method='ffill', axis=0)
/Users/garciaj42/code/MLFinance/claude/fred_collector.py:151: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  features = features.fillna(method='bfill', axis=0)

In [33]:
fred_data

,GDP,UNRATE,CPIAUCSL,FEDFUNDS,T10Y2Y,BAMLH0A0HYM2,WM2NS,INDPRO,HOUST,RSAFS
2016-12-26,19280.084,4.7,243.618,0.65,1.29,4.11,13298.9,98.8158,1190.0,473019.0
2016-12-27,19280.084,4.7,243.618,0.65,1.29,4.11,13298.9,98.8158,1190.0,473019.0
2016-12-28,19280.084,4.7,243.618,0.65,1.25,4.15,13298.9,98.8158,1190.0,473019.0
2016-12-29,19280.084,4.7,243.618,0.65,1.27,4.18,13298.9,98.8158,1190.0,473019.0
2016-12-30,19280.084,4.7,243.618,0.65,1.25,4.21,13298.9,98.8158,1190.0,473019.0
...,...,...,...,...,...,...,...,...,...,...
2024-12-16,29374.914,4.2,316.441,4.64,0.14,2.69,21391.7,101.9621,1289.0,724609.0
2024-12-17,29374.914,4.2,316.441,4.64,0.15,2.75,21391.7,101.9621,1289.0,724609.0
2024-12-18,29374.914,4.2,316.441,4.64,0.15,2.73,21391.7,101.9621,1289.0,724609.0
2024-12-19,29374.914,4.2,316.441,4.64,0.25,2.91,21391.7,101.9621,1289.0,724609.0
2024-12-20,29374.914,4.2,316.441,4.64,0.22,2.91,21391.7,101.9621,1289.0,724609.0

In [34]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

from market_indicator_data import fetch_market_indicators

# Fetch the data
market_indicators_data = fetch_market_indicators(datetime.now() -  timedelta(days=lookback_days))

Successfully fetched data for Gold (GC=F)
Successfully fetched data for USD/JPY (JPY=X)
Successfully fetched data for S&P 500 (^GSPC)
Successfully fetched data for VIX (^VIX)
Successfully fetched data for ASX 200 (Australia) (^AXJO)
Successfully fetched data for FTSE 100 (UK) (^FTSE)
Successfully fetched data for DAX (Germany) (^GDAXI)
Successfully fetched data for EUR/USD (EUR=X)
Successfully fetched data for Crude Oil (CL=F)

ERROR:yfinance:$^NYHILO: possibly delisted; no timezone found

Successfully fetched data for S&P 500 ETF (SPY)
No data available for NYSE New High/Low Index (^NYHILO)
Successfully fetched data for 20+ Year Treasury Bond ETF (TLT)
Successfully fetched data for Investment Grade Corporate Bond ETF (LQD)
Successfully fetched data for Copper (HG=F)

/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:109: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  # Interpolate currencies with time-weighted values
/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:117: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead

/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:117: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.

/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:118: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  # Forward fill ETFs similar to their underlying indices
/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:117: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead

/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:117: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.

/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:118: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  # Forward fill ETFs similar to their underlying indices
/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:117: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead

/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:117: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.

/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:118: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  # Forward fill ETFs similar to their underlying indices
/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:122: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  # Special handling for VIX - use ffill with shorter window
/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:126: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled = df_filled.fillna(method='bfill', axis=0)
/Users/garciaj42/code/MLFinance/claude/market_indicator_data.py:128: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  # Keep the original Date column

In [35]:
market_indicators_data

,GC=F,JPY=X,^GSPC,^VIX,^AXJO,^FTSE,^GDAXI,EUR=X,CL=F,SPY,TLT,LQD,HG=F,Date
datetime,,,,,,,,,,,,,,
2016-12-26 00:00:00,1137.300049,117.309998,2268.879883,11.990000,5685.0,7106.100098,11472.240234,0.956500,53.900002,198.191055,96.072021,88.774559,2.5080,2016-12-26 00:00:00+00:00
2016-12-26 23:00:00,1137.300049,117.196918,2268.879883,11.990000,5685.0,7106.100098,11472.240234,0.956308,53.900002,198.191055,96.072021,88.774559,2.5080,2016-12-26 23:00:00+00:00
2016-12-27 00:00:00,1137.300049,117.192001,2268.879883,11.990000,5685.0,7106.100098,11472.240234,0.956300,53.900002,198.191055,96.072021,88.774559,2.5080,2016-12-27 00:00:00+00:00
2016-12-27 05:00:00,1137.300049,117.252002,2268.879883,11.990000,5685.0,7106.100098,11472.240234,0.956198,53.900002,198.191055,96.072021,88.774559,2.5080,2016-12-27 05:00:00+00:00
2016-12-27 06:00:00,1137.300049,117.264002,2268.879883,11.990000,5685.0,7106.100098,11472.240234,0.956178,53.900002,198.191055,96.072021,88.774559,2.5080,2016-12-27 06:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-19 13:00:00,2592.199951,156.282292,5867.080078,24.090000,8067.0,8105.299805,19969.859375,0.965418,69.910004,584.133972,87.809998,106.559998,4.0205,2024-12-19 13:00:00+00:00
2024-12-19 23:00:00,2592.199951,157.520206,5867.080078,24.090000,8067.0,8105.299805,19884.750000,0.964847,69.910004,584.133972,87.809998,106.559998,4.0205,2024-12-19 23:00:00+00:00
2024-12-20 00:00:00,2592.199951,157.643997,5867.080078,24.090000,8067.0,8084.600098,19884.750000,0.964790,69.910004,584.133972,87.809998,106.559998,4.0205,2024-12-20 00:00:00+00:00
2024-12-20 05:00:00,2628.699951,157.643997,5930.850098,24.090000,8067.0,8084.600098,19884.750000,0.964790,69.459999,591.150024,88.309998,106.980003,4.0410,2024-12-20 05:00:00+00:00
2024-12-20 06:00:00,2628.699951,157.643997,5930.850098,18.360001,8067.0,8084.600098,19884.750000,0.964790,69.459999,591.150024,88.309998,106.980003,4.0410,2024-12-20 06:00:00+00:00

In [36]:
from ib_insync import *

ib = IB()
try:
    # Connect to IB
    ib.connect(host='127.0.0.1', port=7497, clientId=1)
except Exception as e:
    print("Failed to connect to IB Gateway", e)

from continuous_futures_contract import ContinuousFuturesContract

continuous = ContinuousFuturesContract(ib)
market_data = await continuous.get_continuous_contract(underlying="ES", exchange="CME", lookback_days=lookback_days, data_dir="/Users/garciaj42/code/MLFinance/claude/Data/ES_1min")

INFO:continuous_futures_contract:Reading contract H20 from ES_H20_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_H20_1min.txt
INFO:ib_insync.ib:Disconnecting from 127.0.0.1:7497, 117 B sent in 8 messages, 17.1 kB received in 424 messages, session time 2.83 ks.
INFO:ib_insync.client:Disconnecting

Failed to connect to IB Gateway This event loop is already running

INFO:continuous_futures_contract:Successfully loaded 119814 rows from ES_H20_1min.txt
INFO:continuous_futures_contract:Reading contract H21 from ES_H21_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_H21_1min.txt
INFO:continuous_futures_contract:Successfully loaded 118420 rows from ES_H21_1min.txt
INFO:continuous_futures_contract:Reading contract H22 from ES_H22_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_H22_1min.txt
INFO:continuous_futures_contract:Successfully loaded 121541 rows from ES_H22_1min.txt
INFO:continuous_futures_contract:Reading contract H23 from ES_H23_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_H23_1min.txt
INFO:continuous_futures_contract:Successfully loaded 122874 rows from ES_H23_1min.txt
INFO:continuous_futures_contract:Reading contract H24 from ES_H24_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_H24_1min.txt
INFO:continuous_futures_contract:Successfully loaded 120055 rows from ES_H24_1min.txt
INFO:continuous_futures_contract:Reading contract M20 from ES_M20_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_M20_1min.txt
INFO:continuous_futures_contract:Successfully loaded 127861 rows from ES_M20_1min.txt
INFO:continuous_futures_contract:Reading contract M21 from ES_M21_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_M21_1min.txt
INFO:continuous_futures_contract:Successfully loaded 119804 rows from ES_M21_1min.txt
INFO:continuous_futures_contract:Reading contract M22 from ES_M22_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_M22_1min.txt
INFO:continuous_futures_contract:Successfully loaded 128016 rows from ES_M22_1min.txt
INFO:continuous_futures_contract:Reading contract M23 from ES_M23_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_M23_1min.txt
INFO:continuous_futures_contract:Successfully loaded 122352 rows from ES_M23_1min.txt
INFO:continuous_futures_contract:Reading contract M24 from ES_M24_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_M24_1min.txt
INFO:continuous_futures_contract:Successfully loaded 125047 rows from ES_M24_1min.txt
INFO:continuous_futures_contract:Reading contract U20 from ES_U20_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_U20_1min.txt
INFO:continuous_futures_contract:Successfully loaded 135145 rows from ES_U20_1min.txt
INFO:continuous_futures_contract:Reading contract U21 from ES_U21_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_U21_1min.txt
INFO:continuous_futures_contract:Successfully loaded 117875 rows from ES_U21_1min.txt
INFO:continuous_futures_contract:Reading contract U22 from ES_U22_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_U22_1min.txt
INFO:continuous_futures_contract:Successfully loaded 131252 rows from ES_U22_1min.txt
INFO:continuous_futures_contract:Reading contract U23 from ES_U23_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_U23_1min.txt
INFO:continuous_futures_contract:Successfully loaded 119152 rows from ES_U23_1min.txt
INFO:continuous_futures_contract:Reading contract U24 from ES_U24_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_U24_1min.txt
INFO:continuous_futures_contract:Successfully loaded 120053 rows from ES_U24_1min.txt
INFO:continuous_futures_contract:Reading contract Z19 from ES_Z19_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_Z19_1min.txt
INFO:continuous_futures_contract:Successfully loaded 126790 rows from ES_Z19_1min.txt
INFO:continuous_futures_contract:Reading contract Z20 from ES_Z20_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_Z20_1min.txt
INFO:continuous_futures_contract:Successfully loaded 126578 rows from ES_Z20_1min.txt
INFO:continuous_futures_contract:Reading contract Z21 from ES_Z21_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_Z21_1min.txt
INFO:continuous_futures_contract:Successfully loaded 118344 rows from ES_Z21_1min.txt
INFO:continuous_futures_contract:Reading contract Z22 from ES_Z22_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_Z22_1min.txt
INFO:continuous_futures_contract:Successfully loaded 123946 rows from ES_Z22_1min.txt
INFO:continuous_futures_contract:Reading contract Z23 from ES_Z23_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_Z23_1min.txt
INFO:continuous_futures_contract:Successfully loaded 121295 rows from ES_Z23_1min.txt
INFO:continuous_futures_contract:Reading contract Z24 from ES_Z24_1min.txt at /Users/garciaj42/code/MLFinance/claude/Data/ES_1min/ES_Z24_1min.txt
INFO:continuous_futures_contract:Successfully loaded 87128 rows from ES_Z24_1min.txt
INFO:continuous_futures_contract:Final dataset contains 1857446 rows

Sample of loaded data:
                               date_col    open    high     low   close  \
date
2018-09-25 16:08:00 2018-09-25 16:08:00  2947.0  2947.0  2947.0  2947.0
2018-11-27 02:31:00 2018-11-27 02:31:00  2699.5  2699.5  2699.5  2699.5
2018-11-27 11:42:00 2018-11-27 11:42:00  2699.5  2699.5  2699.5  2699.5
2018-11-28 23:59:00 2018-11-28 23:59:00  2766.5  2766.5  2766.5  2766.5
2018-12-04 11:22:00 2018-12-04 11:22:00  2798.0  2798.0  2798.0  2798.0

                     volume sec_col current_sec_col
date
2018-09-25 16:08:00     5.0     Z19             Z19
2018-11-27 02:31:00     1.0     Z19             Z19
2018-11-27 11:42:00     1.0     Z19             Z19
2018-11-28 23:59:00     1.0     Z19             Z19
2018-12-04 11:22:00     1.0     Z19             Z19
Reading data in batches:
Batch number: 0
Returning bars

INFO:ib_insync.client:Connecting to 127.0.0.1:7497 with clientId 1...

Sample of run bars:
            date_time  tick_num    open     high      low    close     volume  \
0 2019-03-22 08:10:00       211  2947.0  2947.00  2424.25  2855.25  580213.75
1 2019-04-09 12:13:00       416  2846.5  2911.00  2800.00  2898.75  585829.75
2 2019-04-25 15:02:00       611  2899.5  2950.25  2889.00  2943.50  569668.50
3 2019-05-06 09:10:00       804  2942.0  2970.00  2898.00  2920.00  567604.25
4 2019-05-10 03:59:00      1011  2920.0  2944.50  2845.00  2878.00  598112.50

   cum_buy_volume  cum_ticks  cum_dollar_value
0       304788.00        211      1.598279e+09
1       314803.25        205      1.674365e+09
2       318690.00        195      1.664236e+09
3       320762.25        193      1.669322e+09
4       271721.00        207      1.728248e+09

INFO:ib_insync.client:Connected

In [37]:
market_data

,date_time,tick_num,open,high,low,close,volume,cum_buy_volume,cum_ticks,cum_dollar_value
date_time,,,,,,,,,,
2019-03-22 08:10:00,2019-03-22 08:10:00,211,2947.00,2947.00,2424.25,2855.25,580213.75,304788.00,211,1.598279e+09
2019-04-09 12:13:00,2019-04-09 12:13:00,416,2846.50,2911.00,2800.00,2898.75,585829.75,314803.25,205,1.674365e+09
2019-04-25 15:02:00,2019-04-25 15:02:00,611,2899.50,2950.25,2889.00,2943.50,569668.50,318690.00,195,1.664236e+09
2019-05-06 09:10:00,2019-05-06 09:10:00,804,2942.00,2970.00,2898.00,2920.00,567604.25,320762.25,193,1.669322e+09
2019-05-10 03:59:00,2019-05-10 03:59:00,1011,2920.00,2944.50,2845.00,2878.00,598112.50,271721.00,207,1.728248e+09
...,...,...,...,...,...,...,...,...,...,...
2024-11-13 16:32:00,2024-11-13 16:32:00,1857419,6020.25,6021.25,6019.75,6021.25,48167.25,30106.00,8,2.899864e+08
2024-11-13 16:41:00,2024-11-13 16:41:00,1857428,6021.50,6022.25,6021.25,6021.75,54198.75,24088.50,9,3.263668e+08
2024-11-13 16:46:00,2024-11-13 16:46:00,1857433,6022.00,6022.25,6022.00,6022.25,30112.25,30112.25,5,1.813405e+08
2024-11-13 16:52:00,2024-11-13 16:52:00,1857439,6021.50,6021.50,6019.50,6019.50,36123.75,0.00,6,2.174815e+08
2024-11-13 16:58:00,2024-11-13 16:58:00,1857445,6020.00,6020.25,6018.25,6018.25,36118.00,12040.50,6,2.174123e+08

In [39]:
# Align all data to market data timestamps
aligned_data = market_data.copy()

In [40]:
### COMBINE FRED 

macro_features = fred_data.reindex(aligned_data.index, method='ffill')
aligned_data = pd.concat([aligned_data, macro_features], axis=1)

In [41]:
### COMBINE YAHOO

market_indicators_data = market_indicators_data.reindex(aligned_data.index, method='ffill')
aligned_data = pd.concat([aligned_data, market_indicators_data], axis=1)

In [42]:
aligned_data

,date_time,tick_num,open,high,low,close,volume,cum_buy_volume,cum_ticks,cum_dollar_value,...,^AXJO,^FTSE,^GDAXI,EUR=X,CL=F,SPY,TLT,LQD,HG=F,Date
date_time,,,,,,,,,,,,,,,,,,,,,
2019-03-22 08:10:00,2019-03-22 08:10:00,211,2947.00,2947.00,2424.25,2855.25,580213.75,304788.00,211,1.598279e+09,...,6195.200195,7207.600098,11364.169922,0.879548,59.040001,255.207352,107.834114,97.554832,2.8360,2019-03-22 05:00:00+00:00
2019-04-09 12:13:00,2019-04-09 12:13:00,416,2846.50,2911.00,2800.00,2898.75,585829.75,314803.25,205,1.674365e+09,...,6221.799805,7425.600098,11850.570312,0.888172,63.980000,262.573334,107.310059,97.915108,2.9315,2019-04-09 05:00:00+00:00
2019-04-25 15:02:00,2019-04-25 15:02:00,611,2899.50,2950.25,2889.00,2943.50,569668.50,318690.00,195,1.664236e+09,...,6385.600098,7434.100098,12282.599609,0.897418,65.209999,266.905243,106.799393,98.402077,2.8775,2019-04-25 14:00:00+00:00
2019-05-06 09:10:00,2019-05-06 09:10:00,804,2942.00,2970.00,2898.00,2920.00,567604.25,320762.25,193,1.669322e+09,...,6283.700195,7380.600098,12286.879883,0.893670,62.250000,267.608978,107.552666,98.585815,2.8370,2019-05-06 05:00:00+00:00
2019-05-10 03:59:00,2019-05-10 03:59:00,1011,2920.00,2944.50,2845.00,2878.00,598112.50,271721.00,207,1.728248e+09,...,6310.899902,7203.299805,12059.830078,0.891100,61.700001,261.979340,108.350655,98.337494,2.7835,2019-05-09 23:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-11-13 16:32:00,2024-11-13 16:32:00,1857419,6020.25,6021.25,6019.75,6021.25,48167.25,30106.00,8,2.899864e+08,...,8224.000000,8030.299805,19003.109375,0.944450,68.430000,595.186829,89.142876,107.483551,4.0660,2024-11-13 13:00:00+00:00
2024-11-13 16:41:00,2024-11-13 16:41:00,1857428,6021.50,6022.25,6021.25,6021.75,54198.75,24088.50,9,3.263668e+08,...,8224.000000,8030.299805,19003.109375,0.944450,68.430000,595.186829,89.142876,107.483551,4.0660,2024-11-13 13:00:00+00:00
2024-11-13 16:46:00,2024-11-13 16:46:00,1857433,6022.00,6022.25,6022.00,6022.25,30112.25,30112.25,5,1.813405e+08,...,8224.000000,8030.299805,19003.109375,0.944450,68.430000,595.186829,89.142876,107.483551,4.0660,2024-11-13 13:00:00+00:00
2024-11-13 16:52:00,2024-11-13 16:52:00,1857439,6021.50,6021.50,6019.50,6019.50,36123.75,0.00,6,2.174815e+08,...,8224.000000,8030.299805,19003.109375,0.944450,68.430000,595.186829,89.142876,107.483551,4.0660,2024-11-13 13:00:00+00:00
2024-11-13 16:58:00,2024-11-13 16:58:00,1857445,6020.00,6020.25,6018.25,6018.25,36118.00,12040.50,6,2.174123e+08,...,8224.000000,8030.299805,19003.109375,0.944450,68.430000,595.186829,89.142876,107.483551,4.0660,2024-11-13 13:00:00+00:00

In [ ]:
from feature_storage import FeatureStorage

fs = FeatureStorage(path_name + "/Data/financial_features.parquet")
fs.save_features(aligned_data)

INFO:ib_insync.wrapper:Warning 2103, reqId -1: Market data farm connection is broken:usfarm
ERROR:ib_insync.wrapper:Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
ERROR:ib_insync.wrapper:Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
INFO:ib_insync.wrapper:Warning 2157, reqId -1: Sec-def data farm connection is broken:secdefil
INFO:ib_insync.wrapper:Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefil
INFO:ib_insync.wrapper:Warning 2104, reqId -1: Market data farm connection is OK:usfarm
ERROR:ib_insync.wrapper:Error 1102, reqId -1: Connectivity between IBKR and Trader Workstation has been restored - data maintained. The following farms are connected: usfarm; secdefil. The following farms are not connected: ushmds.
ERROR:ib_insync.wrapper:Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
INFO:ib_insync.wrapper:Warning 2103, reqId -1: Market data farm connection is broken:usfarm
INFO:ib_insync.wrapper:Warning 2157, reqId -1: Sec-def data farm connection is broken:secdefil
INFO:ib_insync.wrapper:Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefil
INFO:ib_insync.wrapper:Warning 2104, reqId -1: Market data farm connection is OK:usfarm
ERROR:ib_insync.wrapper:Error 1102, reqId -1: Connectivity between IBKR and Trader Workstation has been restored - data maintained. The following farms are connected: usfarm; secdefil. The following farms are not connected: ushmds.
ERROR:ib_insync.wrapper:Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
INFO:ib_insync.wrapper:Warning 2103, reqId -1: Market data farm connection is broken:usfarm
INFO:ib_insync.wrapper:Warning 2157, reqId -1: Sec-def data farm connection is broken:secdefil
INFO:ib_insync.wrapper:Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefil
INFO:ib_insync.wrapper:Warning 2104, reqId -1: Market data farm connection is OK:usfarm
ERROR:ib_insync.wrapper:Error 1102, reqId -1: Connectivity between IBKR and Trader Workstation has been restored - data maintained. The following farms are connected: usfarm; secdefil. The following farms are not connected: ushmds.
ERROR:ib_insync.wrapper:Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
INFO:ib_insync.wrapper:Warning 2103, reqId -1: Market data farm connection is broken:usfarm
INFO:ib_insync.wrapper:Warning 2157, reqId -1: Sec-def data farm connection is broken:secdefil
INFO:ib_insync.wrapper:Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefil
INFO:ib_insync.wrapper:Warning 2104, reqId -1: Market data farm connection is OK:usfarm
ERROR:ib_insync.wrapper:Error 1102, reqId -1: Connectivity between IBKR and Trader Workstation has been restored - data maintained. The following farms are connected: usfarm; secdefil. The following farms are not connected: ushmds.
INFO:ib_insync.wrapper:Warning 2157, reqId -1: Sec-def data farm connection is broken:secdefil
INFO:ib_insync.wrapper:Warning 2103, reqId -1: Market data farm connection is broken:usfarm
INFO:ib_insync.wrapper:Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefil
INFO:ib_insync.wrapper:Warning 2104, reqId -1: Market data farm connection is OK:usfarm